name: Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '*.asciidoc'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Export PR_NUMBER
        run: |
          echo ::set-env name=PR_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      - name: Execute tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :check
      - name: Store hprof files
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: hprofs
          path: ./**/*.hprof
      - name: Publish snapshot
        uses: eskatos/gradle-command-action@v1
        env:
          sonatypeUsername: ${{ secrets.sonatypeUsername }}
          sonatypePassword: ${{ secrets.sonatypePassword }}
        with:
          arguments: :publishToMavenCentral
        
